apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: zabunhub/pipeline-example-frontend:610a48bdcf3f9f5962ff7f48dd752c13002be0ae  # Replace with your actual image
        ports:
        - containerPort: 3000
      # Add any necessary environment variables or volume mounts here
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001  # Adjust the NodePort as needed