name: Release yaml

on:
  pull_request:
    branches:
      - main
    
  workflow_dispatch:

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
            context: ./pipeline-example/frontend
            push: true
            tags: zabunhub/pipeline-example-frontend:${{ github.sha }}
            file: ./pipeline-example/frontend/Dockerfile
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
            context: ./pipeline-example/backend
            push: true
            tags: zabunhub/pipeline-example-backend:${{ github.sha }}
            file: ./pipeline-example/backend/Dockerfile